[package]
name = "syn-internal-codegen"
version = "0.0.0"
authors = ["Nika Layzell <nika@thelayzells.com>"]
edition = "2018"

publish = false # this is an internal crate which should never be published

[dependencies]
syn = { path = "..", features = ["full", "extra-traits"] }
quote = "0.6"
failure = "0.1"
indexmap = { version = "1.0", features = ["serde-1"] }
inflections = "1.1"
proc-macro2 = "0.4"
rustfmt = { package = "rustfmt-nightly", git = "https://github.com/rust-lang-nursery/rustfmt" }
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0.38"
toml = "0.4.10"
semver = { version = "0.9", features = ["serde"] }
syn-codegen = { path = "../json" }

[workspace]
# Prefer that `cargo clean` in syn's directory does not require a rebuild of
# rustfmt in the codegen directory.
